### ISSUE TITLE
is this right

### ISSUE THREAD

**Issue by hdmjdp** [yerfor/SyntaSpeech#1]
https://github.com/yerfor/SyntaSpeech/blob/d4f300ecd6d5670e90a1129b5f391a368709206b/modules/tts/syntaspeech/syntactic_graph_encoder.py#L153

**Comment by yerfor** [comment]
Thanks for your helpful comment. This is a mistake during our re-implementation in the released code. We have fixed it it a recent commit 64dc2f2. Thank you again!

**Comment by hdmjdp** [comment]
顺便请教一下，开源的code里面的句法分析是用的stanza，那你们论文里用的是否也是这个工具

**Comment by yerfor** [comment]
Yes, in the paper, we used stanza to extract dependency trees from the English and Chinese text.
