### ISSUE TITLE
For Multi-speaker Chinese data

### ISSUE THREAD

**Issue by bingyulab** [yerfor/SyntaSpeech#2]
I saw you have trained on libriTTS dataset. Have you test on AISHELL3 or other multi speaker chinese data?
Not so good or other situation?

**Comment by yerfor** [comment]
Hi there, we have not tested SyntaSpeech on multi speaker chinese dataset.
Ideally, it should work well.

**Comment by Summerxu86** [comment]
Hello, may I ask whether you have achieved the training of Aishell3 Chinese multi-person dataset? Or can you give me some Pointers and help? I'm very upset at the moment
