### ISSUE TITLE
A question of KL divergence calculation

### ISSUE THREAD

**Issue by JiaYK** [yerfor/SyntaSpeech#6]
In modules/tts/portaspeech/fvae.py, SyntaFVAE compute loss_kl (line 121) , Can someone help explain why
` loss_kl = ((logqx - logpx) * nonpadding_sqz).sum() / nonpadding_sqz.sum() / logqx.shape[1]`，I think loss_kl should be compute by `loss_kl = logqx.exp()*(logqx - logpx) `
I would be very grateful if you could reply to me！

**Comment by yerfor** [comment]
Hi there, this code is borrowed from the official code of PortaSpeech.
We recommend you to refer to the equation (3) of the PortaSpeech paper.

**Comment by JiaYK** [comment]
Thank you very much for your reply. 
After reading the paper, I understand the meaning of equation (3).
This is not a standard KL divergence, but the effect is really very good.
