### ISSUE TITLE
discriminator output['y_c'] never used

### ISSUE THREAD

**Issue by mayfool** [yerfor/SyntaSpeech#7]
Discriminator's output['y_c'] never used, and never calculated in discriminator forward func. What does this variable mean?
https://github.com/yerfor/SyntaSpeech/blob/5b07439633a3e714d2a6759ea4097eb36d6cd99a/tasks/tts/synta.py#L81

**Comment by yerfor** [comment]
Hi there, this is some history code that needs to be deleted. In the current code, this line will never be called.
Actually, 'y_c' is the abbreviation of 'y_conditioned'. We have tried discriminators conditioned on other features, but it doesn't bring noticeable improvement.

**Comment by mayfool** [comment]
Thanks for reply.

> Hi there, this is some history code that needs to be deleted. In the current code, this line will never be called. Actually, 'y_c' is the abbreviation of 'y_conditioned'. We have tried discriminators conditioned on other features, but it doesn't bring noticeable improvement.
