### ISSUE TITLE
pinyin preprocess problem

### ISSUE THREAD

**Issue by windowxiaoming** [yerfor/SyntaSpeech#8]
005804	你当#1我傻啊#3？脑子#1那么大#2怎么#1塞进去#4？
	ni3 dang1 wo2 sha3 a5 nao3 zi5 na4 me5 da4 zen3 me5 sai1 jin4 qu4

txt_struct=[['<BOS>', ['<BOS>']], ['你', ['n', 'i3']], ['当', ['d', 'ang1']], ['我', ['uo3']], ['傻', ['sh', 'a3']], ['啊', ['a', '?', 'n', 'ao3']], ['?', ['z', 'i']], ['脑', ['n', 'a4']], ['子', ['m', 'e']], ['那', ['d', 'a4']], ['么', ['z', 'en3']], ['大', ['m', 'e']], ['怎', ['s', 'ai1']], ['么', ['j', 'in4']], ['塞', ['q', 'v4', '?']], ['进', []], ['去', []], ['?', []], ['<EOS>', ['<EOS>']]]

ph_gb_word=['<BOS>', 'n_i3', 'd_ang1', 'uo3', 'sh_a3', 'a_?_n_ao3', 'z_i', 'n_a4', 'm_e', 'd_a4', 'z_en3', 'm_e', 's_ai1', 'j_in4', 'q_v4_?', '', '', '', '<EOS>']

what is  'a_?_n_ao3'

in the mfa_dict it appears ch_a1_d_ou1 ,a_?_n_ao3 and so on

**Comment by yerfor** [comment]
Hi there, this is a bug in `data_gen/tts/txt_processors/zh.py`, and I have solved it in the latest commit. To be specific, the previous code ignores the "?" or "!" when separating the words. I have made small modifications as follows, please refer to line 95-96 in `data_gen/tts/txt_processors/zh.py` for details.

            # elif ph in [',', '.']:
            elif ph in [',', '.', '?', '!']:

**Comment by windowxiaoming** [comment]
@yerfor thank you for your reply,i will attempt to run the modification
